# Generated by Django 3.1.7 on 2021-03-18 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hos_name', models.CharField(max_length=50)),
                ('hos_email', models.EmailField(max_length=254)),
                ('hos_number', models.IntegerField()),
                ('hos_location', models.CharField(max_length=50)),
                ('hos_password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('med_nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pha_name', models.CharField(max_length=50)),
                ('pha_email', models.CharField(max_length=50)),
                ('pha_number', models.IntegerField()),
                ('pha_location', models.CharField(max_length=50)),
                ('pha_password', models.CharField(max_length=50)),
                ('pha_status', models.CharField(max_length=50)),
                ('pha_garde', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('us_firstname', models.CharField(max_length=50)),
                ('us_lastname', models.CharField(max_length=50)),
                ('us_email', models.EmailField(max_length=50)),
                ('us_number', models.IntegerField()),
                ('us_birthday', models.DateField()),
                ('us_password', models.CharField(max_length=50)),
                ('us_status', models.CharField(max_length=50)),
                ('us_city', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rdv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rdv_date', models.DateField()),
                ('rdv_status', models.CharField(max_length=50)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hospital')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ord_date', models.DateField()),
                ('ord_status', models.CharField(max_length=50)),
                ('hospital', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.hospital')),
                ('medicament', models.ManyToManyField(blank=True, db_table='constitue', related_name='ordonnance', to='api.Medicament')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.AddField(
            model_name='hospital',
            name='user',
            field=models.ManyToManyField(related_name='hospital', through='api.Rdv', to='api.User'),
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_date', models.DateField()),
                ('com_status', models.CharField(max_length=50)),
                ('pharmacie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pharmacie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
